<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>TileIconifier.Core</RootNamespace>
    <AssemblyName>TileIconifier.Core</AssemblyName>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <Copyright>Copyright ©  2021</Copyright>
    <AssemblyVersion>3.1.2</AssemblyVersion>
  </PropertyGroup>
  
  <PropertyGroup>
    <ApplicationIcon>tiles2_shadow_lyk_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ClearScript.Windows" Version="7.5.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.11" />
    <PackageReference Include="System.Management.Automation" Version="7.6.4" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.11" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="Resources\Google-Chrome-icon.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\explorer_ICO_MYCOMPUTER.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Steam.ico" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="FodyWeavers.xml" />
    <Content Include="tiles2_shadow_lyk_icon.ico" />
  </ItemGroup>
  
</Project>